site_name: PhishDetect
repo_url: https://github.com/phishdetect/phishdetect.github.io
edit_uri: edit/main/docs/
copyright: (c) 2020 Claudio Guarnieri
site_description: PhishDetect documentation for administrators
theme: readthedocs
